development:
  adapter: postgresql
  database: oms_development
  encoding: unicode
  username: devuser
  password: devuser
  host: localhost
test:
  adapter: postgresql
  database: oms_test<%= ENV['TEST_ENV_NUMBER'] %>
  encoding: unicode
  username: devuser
  password: devuser
  host: localhost
