development:
  adapter: postgresql
  database: sample_app_development
  encoding: unicode
  username: devuser
  password: devuser
  host: localhost
test:
  adapter: postgresql
  database: sample_app_test<%= ENV['TEST_ENV_NUMBER'] %>
  encoding: unicode
  username: devuser
  password: devuser
  host: localhost
